{"_id":"ByVffBEyV","title":"ValueError: Error when checking input: expected dense_1_input to have shape (3,) but got array with shape (1,)","body":{"entityMap":{},"blocks":[{"key":"ag6qs","text":"ValueError: Error when checking input: expected dense_1_input to have shape (3,) but got array with shape (1,)","type":"header-one","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"9m0vs","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"fe4qu","text":"Suppose we are giving feeding input to a tensorflow model like this","type":"header-two","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"soos","text":"model.predict(x_in)","type":"custom-code-block-python","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"59kd9","text":"and we get the given error, then we do the following","type":"header-two","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"175s5","text":"if(x_in.ndim == 1):","type":"custom-code-block-python","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"uuqg","text":"    x = np.array([x])","type":"custom-code-block-python","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}]},"dateCreated":"2018-12-04T18:06:03.864Z","lastUpdated":"2018-12-04T18:08:24.226Z"}
